CREATE TABLE IF NOT EXISTS filmorate_user (
user_id int GENERATED BY DEFAULT AS IDENTITY,
email varchar(255) NOT NULL,
login varchar(255) NOT NULL,
name varchar(255),
birthday date,
PRIMARY KEY (user_id)
);

CREATE TABLE IF NOT EXISTS user_friends (
user_id int,
friend_id int,
status varchar(30),
PRIMARY KEY (user_id, friend_id),
FOREIGN KEY (user_id) REFERENCES filmorate_user(user_id)
);

CREATE TABLE IF NOT EXISTS films (
film_id int generated by default as identity primary key,
name varchar(255) NOT NULL,
description varchar(255) NOT NULL,
duration int,
likes long,
release_date date
);

CREATE TABLE IF NOT EXISTS mpa (
mpa_id int PRIMARY KEY,
title varchar
);

CREATE TABLE IF NOT EXISTS mpa_list (
film_id int,
mpa_id int,
PRIMARY KEY (film_id, mpa_id),
FOREIGN KEY (film_id) REFERENCES films(film_id),
FOREIGN KEY (mpa_id) REFERENCES mpa(mpa_id)
);

CREATE TABLE IF NOT EXISTS genre (
genre_id int PRIMARY KEY,
title varchar
);

CREATE TABLE IF NOT EXISTS genre_list (
film_id int,
genre_id int,
PRIMARY KEY (film_id, genre_id),
FOREIGN KEY (film_id) REFERENCES films(film_id),
FOREIGN KEY (genre_id) REFERENCES genre(genre_id)
);